GET http://localhost:3000/inventory/make

###

POST http://localhost:3000/inventory/make/
Content-Type: application/json

{
  "name": "Scion"
}

###
DELETE http://localhost:3000/inventory/make/622e999bc59b75990b045eb3/delete

### 

PUT http://localhost:3000/inventory/make/622e766deffff85b942e3088/put
Content-Type: application/json

{
  "name": "Mclaren"
}

### 

GET http://localhost:3000/inventory/automobiles/

### 

POST http://localhost:3000/inventory/automobiles/
Content-Type: application/json

{
  "make" : "Scion",
  "engine" : "v4",
  "model" : "xB",
  "year" : 2006,
  "price" : 5000,
}